### ISSUE TITLE
Openrepos release

### ISSUE THREAD

**Issue by Kabouik** [jgibbon/yikes#20]
Hey @jgibbon, just wondering if you plan to release Yikes on openrepos.net. I know it's still missing some features, but could already be useful, and Yi cameras are not outdated yet.

I needed to connect to my Yi 4k yesterday, after a long time not using it. I had to search the official Android app everywhere since it didn't seem to be on the Play store (using Aurora). Finally found it on a dedicated Xiaomi website. Installed it. Connected to the Yi WiFi hotspot. Could not pair with it (adhoc WiFi issue with apks?).

Then I remembered I beta tested Yikes years ago. Downloaded the rpm from here, paired instantly, voilà. I would probably have remembered it earlier if it had been released officially, and I'm sure many users don't know about it.

**Comment by jgibbon** [comment]
Hi!
I'm glad it worked for you. 
But trying to get different camera models (or possibly even firmware versions) to work, especially without having the devices, turned out to be pretty much impossible. 
As such, yikes does not meet my quality requirements for a broader release. It's a bit of a pity, since the UI mostly worked pretty well for simple use cases – it's just hard to ensure a working "back end". 

I don't rule out revisiting the development of this project at some point, also PRs are still welcome if someone has the skills, time and hardware to do so.

cheers!
